org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=false
maven.repo.local=C:/Users/AdminZhao/.m2/repository

minecraft_version=26.1.2
neo_version=26.1.2.76
mod_group_id=com.mistbeyond
mod_version=1.0.0
